--INSERT INTO users (email, login, name)
--SELECT * FROM (SELECT 'john@mail.ru' AS email, 'robot' AS login, 'robobot' AS name)
--WHERE NOT EXISTS (
--SELECT email FROM users WHERE email='john@mail.ru'
--);
DELETE FROM users;

INSERT INTO MPA (MPA_ID, NAME) VALUES (1, 'G');
INSERT INTO MPA (MPA_ID, NAME) VALUES (2, 'PG');
INSERT INTO MPA (MPA_ID, NAME) VALUES (3, 'PG-13');
INSERT INTO MPA (MPA_ID, NAME) VALUES (4, 'R');
INSERT INTO MPA (MPA_ID, NAME) VALUES (5, 'NC-17');

INSERT INTO GENRE (GENRE_ID, NAME) VALUES (1, 'COMEDY("Комедия")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (2, 'DRAMA("Драма")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (3, 'CARTOON("Мультфильм")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (4, 'THRILLER("Триллер")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (5, 'DOCUMENTARY("Документальный")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (6, 'ACTION("Боевик")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (7, 'FANTASTIC("Фантастика")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (8, 'FANTASY("Фэнтази")');
INSERT INTO GENRE (GENRE_ID, NAME) VALUES (9, 'HORRORS("Ужасы")');